import { image } from './image';

export const strategyBlock = [
	{
		id: 1,
		lightningIcon: true,
		title: 'Упаковка опыта',
		description: 'Любой опыт можно продать как сильный — мы покажем как.',
	},
	{
		id: 2,
		lightningIcon: false,
		title: 'ATS и автофильтры',
		description: 'Пройти отбор и выделиться среди сотен кандидатов.',
		imgBoolean: true,
		imgPhone: true,
		imgSrc: image.mentorPhone,
		widthMin: 140,
		widthMax: 220,
		alt: 'Выбор направления',
	},
	{
		id: 3,
		lightningIcon: true,
		title: 'Стратегия поиска',
		description: 'Как правильно искать работу и действовать на рынке.',
	},
	{
		id: 4,
		lightningIcon: true,
		title: 'Подготовка к собесам',
		description: 'Тренируйся с людьми, проходи моки и смотри реальные собесы.',
		imgBoolean: true,
		imgPhone: false,
		imgSrc: image.mentorQuestions,
		heightMin: 80,
		heightMax: 129,
		widthMin: 211,
		alt: 'База вопросов',
	},
	{
		id: 5,
		lightningIcon: true,
		title: 'Реальный опыт',
		description: 'Пет-проекты никому не нужны. Работай на настоящем продакшне.',
	},
	{
		id: 6,
		lightningIcon: true,
		title: 'Мотивация',
		description: 'Будь в окружении людей с одной целью — оффер.',
		imgBoolean: true,
		imgPhone: false,
		imgSrc: image.mentors,
		heightMax: 150,
		heightMin: 88,
		alt: 'Наши менторы',
	},
] as const;
