export {
	DEFAULT_SPECIALIZATION_NUMBER,
	MAX_LIMIT_CATEGORIES,
	MAX_CHOOSE_QUESTION_COUNT,
	COLLECTION_QUESTIONS_LIMIT,
	MAX_LIMIT_RESOURCES,
	QUESTIONS_PER_PAGE,
	DEFAULT_SPECIALIZATION_SLUG,
} from './queryConstants';

export { SPEC_MAP, SPEC_MAP_TO_TITLE } from './mappingStaticParams';

export { route } from './route';
