export {
	COUNT_TO_GET_QUESTIONS_FOR_SSG,
	COUNT_TO_GET_COLLECTIONS_FOR_SSG,
	DEFAULT_SPECIALIZATION_NUMBER,
	MAX_LIMIT_CATEGORIES,
	MAX_CHOOSE_QUESTION_COUNT,
	COLLECTION_QUESTIONS_LIMIT,
	MAX_LIMIT_RESOURCES,
	QUESTIONS_PER_PAGE,
	DEFAULT_SPECIALIZATION_SLUG,
	RESOURCES_PER_PAGE,
} from './queryConstants';

export { SPEC_MAP, SPEC_MAP_TO_TITLE, getSpecializationSlugById } from './mappingStaticParams';

export { route } from './route';
