export const SPEC_MAP = {
	'react-developer': 11,
	'python-developer': 19,
	'nodejs-developer': 21,
	'system-software-engineer': 39,
	'desktop-application-developer': 40,
	'golang-backend-developer': 23,
	'php-backend-developer': 24,
	'ruby-backend-developer': 25,
	'ios-mobile-developer': 26,
	'android-mobile-developer': 27,
	'rust-backend-developer': 28,
	'qa-engineer': 29,
	'c-c++-backend-developer': 32,
	'c-sharp-backend-developer': 33,
	'data-scientist': 34,
	'game-developer': 35,
	'devops-engineer': 36,
	'machine-learning-engineer': 37,
	'java-backend-developer': 20,
	'1c-developer': 38,
	'system-analyst': 42,
	'1c-analyst': 43,
	'business-analyst': 44,
} as const;

export const SPEC_MAP_TO_TITLE = {
	'react-developer': 'React Frontend Developer',
	'python-developer': 'Python Backend Developer',
	'nodejs-developer': 'Node.js Backend Developer',
	'system-software-engineer': 'System Software Engineer',
	'desktop-application-developer': 'Desktop Application Developer',
	'golang-backend-developer': 'Golang Backend Developer',
	'php-backend-developer': 'PHP Backend Developer',
	'ruby-backend-developer': 'Ruby Backend Developer',
	'ios-mobile-developer': 'iOS Mobile Developer',
	'android-mobile-developer': 'Android Mobile Developer',
	'rust-backend-developer': 'Rust Backend Developer',
	'qa-engineer': 'QA Engineer',
	'c-c++-backend-developer': 'C/C++ Backend Developer',
	'c-sharp-backend-developer': 'C# Backend Developer',
	'data-scientist': 'Data Scientist',
	'game-developer': 'Game Developer',
	'devops-engineer': 'DevOps Engineer',
	'machine-learning-engineer': 'Machine Learning Engineer',
	'java-backend-developer': 'Java Backend Developer',
	'1c-developer': '1C Программист',
	'system-analyst': 'System Analyst',
	'1c-analyst': '1C Аналитик',
	'business-analyst': 'Business Analyst',
} as const;
