export { default as logoDark } from './icons/logoDark.avif';
export { default as logoLight } from './icons/logoLight.avif';
export { default as LogoText } from './icons/logoText.svg';
export { default as interviewBanner } from './images/interviewBanner.png';
// export { default as html5 } from './icons/html5.svg';
// export { default as css3 } from './icons/css3.svg';
// export { default as js } from './icons/js.svg';
// export { default as react } from './icons/react.svg';
// export { default as redux } from './icons/redux.svg';
// export { default as ts } from './icons/ts.svg';
// export { default as n8n } from './icons/n8n.svg';
// export { default as fsd } from './icons/fsd.svg';
// export { default as github_stack } from './icons/github_stack.svg';
// export { default as docker } from './icons/docker.svg';
// export { default as kubernetes } from './icons/kubernetes.svg';
// export { default as ci_cd } from './icons/ci_cd.svg';
// export { default as webpack } from './icons/webpack.svg';
// export { default as storybook } from './icons/storybook.svg';
// export { default as next } from './icons/next.svg';
